# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Mon May 21 13:40:46 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gbReqList = QtGui.QGroupBox(self.centralwidget)
        self.gbReqList.setGeometry(QtCore.QRect(280, 10, 511, 541))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbReqList.sizePolicy().hasHeightForWidth())
        self.gbReqList.setSizePolicy(sizePolicy)
        self.gbReqList.setObjectName("gbReqList")
        self.formLayoutWidget = QtGui.QWidget(self.gbReqList)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 491, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.tableWidget = QtGui.QTableWidget(self.gbReqList)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 491, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gbReqFiles = QtGui.QGroupBox(self.centralwidget)
        self.gbReqFiles.setGeometry(QtCore.QRect(10, 10, 251, 241))
        self.gbReqFiles.setObjectName("gbReqFiles")
        self.treeView = QtGui.QTreeView(self.gbReqFiles)
        self.treeView.setGeometry(QtCore.QRect(10, 21, 231, 211))
        self.treeView.setRootIsDecorated(True)
        self.treeView.setUniformRowHeights(False)
        self.treeView.setAnimated(True)
        self.treeView.setObjectName("treeView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_AddFile = QtGui.QAction(MainWindow)
        self.action_AddFile.setObjectName("action_AddFile")
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setStatusTip("")
        self.action_Quit.setWhatsThis("")
        self.action_Quit.setObjectName("action_Quit")
        self.action_AboutReqExt = QtGui.QAction(MainWindow)
        self.action_AboutReqExt.setObjectName("action_AboutReqExt")
        self.action_AboutPython = QtGui.QAction(MainWindow)
        self.action_AboutPython.setObjectName("action_AboutPython")
        self.menuFile.addAction(self.action_AddFile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menuHelp.addAction(self.action_AboutReqExt)
        self.menuHelp.addAction(self.action_AboutPython)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Search for requirements ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Search for requirments content:", None, QtGui.QApplication.UnicodeUTF8))
        self.gbReqFiles.setTitle(QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_AddFile.setText(QtGui.QApplication.translate("MainWindow", "Add file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setToolTip(QtGui.QApplication.translate("MainWindow", "Exit application", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_AboutReqExt.setText(QtGui.QApplication.translate("MainWindow", "About Requirement Extractor", None, QtGui.QApplication.UnicodeUTF8))
        self.action_AboutPython.setText(QtGui.QApplication.translate("MainWindow", "About Python", None, QtGui.QApplication.UnicodeUTF8))

