# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'req_extractor.ui'
#
# Created: Tue May 15 10:30:33 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 400)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(530, 360, 241, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 220, 780, 140))
        self.groupBox.setObjectName("groupBox")
        self.textBrowser = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 760, 110))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.textBrowser.setFont(font)
        self.textBrowser.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textBrowser.setTabChangesFocus(False)
        self.textBrowser.setDocumentTitle("")
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setTabStopWidth(120)
        self.textBrowser.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.textBrowser.setOpenExternalLinks(False)
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 401, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.leOutputDocPath = QtGui.QLineEdit(self.gridLayoutWidget)
        self.leOutputDocPath.setObjectName("leOutputDocPath")
        self.gridLayout.addWidget(self.leOutputDocPath, 5, 0, 1, 1)
        self.lRegex = QtGui.QLabel(self.gridLayoutWidget)
        self.lRegex.setObjectName("lRegex")
        self.gridLayout.addWidget(self.lRegex, 2, 0, 1, 1)
        self.leRegex = QtGui.QLineEdit(self.gridLayoutWidget)
        self.leRegex.setObjectName("leRegex")
        self.gridLayout.addWidget(self.leRegex, 3, 0, 1, 1)
        self.lInputDoc = QtGui.QLabel(self.gridLayoutWidget)
        self.lInputDoc.setObjectName("lInputDoc")
        self.gridLayout.addWidget(self.lInputDoc, 0, 0, 1, 1)
        self.lOutputDoc = QtGui.QLabel(self.gridLayoutWidget)
        self.lOutputDoc.setObjectName("lOutputDoc")
        self.gridLayout.addWidget(self.lOutputDoc, 4, 0, 1, 1)
        self.bOutputDoc = QtGui.QToolButton(self.gridLayoutWidget)
        self.bOutputDoc.setObjectName("bOutputDoc")
        self.gridLayout.addWidget(self.bOutputDoc, 5, 1, 1, 1)
        self.bInputDoc = QtGui.QToolButton(self.gridLayoutWidget)
        self.bInputDoc.setObjectName("bInputDoc")
        self.gridLayout.addWidget(self.bInputDoc, 1, 1, 1, 1)
        self.leInputDocPath = QtGui.QLineEdit(self.gridLayoutWidget)
        self.leInputDocPath.setObjectName("leInputDocPath")
        self.gridLayout.addWidget(self.leInputDocPath, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(440, 10, 350, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.bExtractReq = QtGui.QPushButton(self.groupBox_3)
        self.bExtractReq.setGeometry(QtCore.QRect(120, 100, 111, 31))
        self.bExtractReq.setObjectName("bExtractReq")
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 331, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.progressBar = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 331, 68))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.cbWordShow = QtGui.QCheckBox(self.formLayoutWidget)
        self.cbWordShow.setObjectName("cbWordShow")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.cbWordShow)
        self.cbExcelShow = QtGui.QCheckBox(self.formLayoutWidget)
        self.cbExcelShow.setChecked(True)
        self.cbExcelShow.setObjectName("cbExcelShow")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.cbExcelShow)
        self.cbWordQuit = QtGui.QCheckBox(self.formLayoutWidget)
        self.cbWordQuit.setObjectName("cbWordQuit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.cbWordQuit)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.leInputDocPath, self.bInputDoc)
        Dialog.setTabOrder(self.bInputDoc, self.leRegex)
        Dialog.setTabOrder(self.leRegex, self.leOutputDocPath)
        Dialog.setTabOrder(self.leOutputDocPath, self.bOutputDoc)
        Dialog.setTabOrder(self.bOutputDoc, self.bExtractReq)
        Dialog.setTabOrder(self.bExtractReq, self.textBrowser)
        Dialog.setTabOrder(self.textBrowser, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Requirements Extractor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Console output", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Requirements Extractor started. (c) Thomas Bores 2012 (http://blog.bores.fr)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "User inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.leOutputDocPath.setText(QtGui.QApplication.translate("Dialog", "exported_RequirementsExample.xls", None, QtGui.QApplication.UnicodeUTF8))
        self.lRegex.setText(QtGui.QApplication.translate("Dialog", "Regular expression for Requirement ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.leRegex.setText(QtGui.QApplication.translate("Dialog", "REQ-EX-*", None, QtGui.QApplication.UnicodeUTF8))
        self.lInputDoc.setText(QtGui.QApplication.translate("Dialog", "Input word document:", None, QtGui.QApplication.UnicodeUTF8))
        self.lOutputDoc.setText(QtGui.QApplication.translate("Dialog", "Output excel document:", None, QtGui.QApplication.UnicodeUTF8))
        self.bOutputDoc.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.bInputDoc.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.leInputDocPath.setText(QtGui.QApplication.translate("Dialog", "RequirementsExample.doc", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.bExtractReq.setText(QtGui.QApplication.translate("Dialog", "Extract requirements", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Progress:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbWordShow.setText(QtGui.QApplication.translate("Dialog", "Show Microsoft Word file during extraction", None, QtGui.QApplication.UnicodeUTF8))
        self.cbExcelShow.setText(QtGui.QApplication.translate("Dialog", "Show ouput Microsoft Excel file", None, QtGui.QApplication.UnicodeUTF8))
        self.cbWordQuit.setText(QtGui.QApplication.translate("Dialog", "Quit Microsoft Word after extraction", None, QtGui.QApplication.UnicodeUTF8))

